#include "annul_define.h"
#define mio_smp_nodo_pv ivan_smp_pv_node_white
#define tuo_smp_nodo_pv ivan_smp_pv_node_black
#define mio_smp_nodo_all ivan_smp_all_node_white
#define tuo_smp_nodo_all ivan_smp_all_node_black
#define mio_smp_nodo_cut ivan_smp_cut_node_white
#define tuo_smp_nodo_cut ivan_smp_cut_node_black

#define mio_pv_cerca_fine pv_cerca_fine_bianco
#define mio_pv_cerca_fine_scacco pv_cerca_fine_scacco_bianco
#define mio_cerca_fine cerca_fine_bianco
#define mio_cerca_fine_scacco cerca_fine_scacco_bianco
#define mio_cerca_mezzo cerca_mezzo_bianco
#define mio_cerca_mezzo_scacco cerca_mezzo_scacco_bianco
#define mio_escludo escludo_bianco
#define mio_escludo_scacco escludo_scacco_bianco
#define mio_nodo_tagliato nodo_tagliato_bianco
#define mio_nodo_tagliato_scacco nodo_tagliato_scacco_bianco
#define mio_nodo_totale nodo_totale_bianco
#define mio_nodo_totale_scacco nodo_totale_scacco_bianco
#define mio_nodo_pv nodo_pv_bianco
#define mio_nodo_superiore nodo_superiore_bianco
#define mio_alto cerca_alto_bianco
#define mio_attaco DINAMICO->attacco_bianco
#define tuo_attaco DINAMICO->attacco_nero
#define mio_attaco_pedone attaco_pedone_bianco
#define tuo_attaco_pedone attaco_pedone_nero
#define tuo_pv_cerca_fine pv_cerca_fine_nero
#define tuo_pv_cerca_fine_scacco pv_cerca_fine_scacco_nero
#define tuo_cerca_fine cerca_fine_nero
#define tuo_cerca_fine_scacco cerca_fine_scacco_nero
#define tuo_cerca_mezzo cerca_mezzo_nero
#define tuo_cerca_mezzo_scacco cerca_mezzo_scacco_nero
#define tuo_escludo escludo_nero
#define tuo_escludo_scacco escludo_scacco_nero
#define tuo_nodo_tagliato nodo_tagliato_nero
#define tuo_nodo_tagliato_scacco nodo_tagliato_scacco_nero
#define tuo_nodo_totale nodo_totale_nero
#define tuo_nodo_totale_scacco nodo_totale_scacco_nero
#define tuo_nodo_pv nodo_pv_nero
#define tuo_nodo_superiore nodo_superiore_nero
#define tuo_alto cerca_alto_nero
#define tuo_occupato bitbordo_occupato_nero
#define bitbordo_tuo_pedone bitbordo_nero_pedone
#define bitbordo_tuo_cavallo bitbordo_nero_cavallo
#define bitbordo_tuo_chiaro bitbordo_nero_chiaro
#define bitbordo_tuo_scuro bitbordo_nero_scuro
#define bitbordo_tuo_alfiere (bitbordo_tuo_chiaro|bitbordo_tuo_scuro)
#define bitbordo_tuo_torre bitbordo_nero_torre
#define bitbordo_tuo_donna bitbordo_nera_donna
#define bitbordo_tuo_re bitbordo_nero_re
#define mio_occupato bitbordo_occupato_bianco
#define bitbordo_mio_pedone bitbordo_bianco_pedone
#define bitbordo_mio_cavallo bitbordo_bianco_cavallo
#define bitbordo_mio_chiaro bitbordo_bianco_chiaro
#define bitbordo_mio_scuro bitbordo_bianco_scuro
#define bitbordo_mio_alfiere (bitbordo_mio_chiaro|bitbordo_mio_scuro)
#define bitbordo_mio_torre bitbordo_bianco_torre
#define bitbordo_mio_donna bitbordo_bianca_donna
#define bitbordo_mio_re bitbordo_bianco_re
#define mio_quadretto_re POSIZIONE->bianco_re_quadretto
#define tuo_quadretto_re POSIZIONE->nero_re_quadretto
#define conto_tuo_pedone conto_pedone_nero
#define conto_tuo_cavallo conto_cavallo_nero
#define conto_tuo_chiaro conto_chiaro_nero
#define conto_tuo_scuro conto_scuro_nero
#define conto_tuo_torre conto_torre_nero
#define conto_tuo_donna conto_donna_nera
#define conto_tuo_re conto_re_nero
#define conto_mio_pedone conto_pedone_bianco
#define conto_mio_cavallo conto_cavallo_bianco
#define conto_mio_chiaro conto_chiaro_bianco
#define conto_mio_scuro conto_scuro_bianco
#define conto_mio_torre conto_torre_bianco
#define conto_mio_donna conto_donna_bianca
#define conto_mio_re conto_re_bianco
#define tuo_re_scacco DINAMICO->nero_re_scacco
#define mio_cattura cattura_bianca
#define mio_ordinaria ordinaria_bianca
#define mio_guadagno guadagno_bianco
#define mio_evasione evasione_bianco
#define mio_scacco_zitto scacco_zitto_bianco
#define mio_SEE SEE_bianca
#define FARE fare_bianco
#define ANNULLA annullare_bianco
#define mossa_illegale mossa_bianco_in_scacco
#define mossa_scacco mossa_nero_in_scacco
#define mio_garantire garantire_bianco
#define mio_prossimo prossimo_bianco
#define mio_nullo ((DINAMICO->pietras)&2)
#define TRAVERSA_QUARTA(x) ((x)>=A4)
#define TRAVERSA_SESTA(x) ((x)>=A6)
#define bitbordo_traversa_quarta TRAVERSA4
#define pedone_libero pedone_libero_bianco
#define mio_xray (DINAMICO->bianco_xray)
#define tuo_xray (DINAMICO->nero_xray)
#define mio_xray_lista xray_bianco_lista
#define tuo_xray_lista xray_nero_lista
#define mio_re_scacco DINAMICO->bianco_re_scacco
#define mio_conto conto_bianco
#define mio_conto_fuggio conto_bianco_fuggio
#define SCACCO bianco_in_scacco

#define TRAVERSA_OTTAVA(x) (x>=A8)
#define cattura_retta ((bitbordo_bianco_pedone&~COLONNAh)<<9)
#define di_sinistra(x) (((x)-9)<<6)
#define cattura_sinistra ((bitbordo_bianco_pedone&~COLONNAa)<<7)
#define di_retto(x) (((x)-7)<<6)
#define avanti(x) ((x)+8)
#define avanti_sinistra(x) ((x)+7)
#define avanti_retto(x) ((x)+9)
#define indietro(x) ((x)-8)
#define avanti_turno(x) ((x)<<8)
#define indietro_turno(x) ((x)>>8)
#define TRAVERSA_SETTIMA(x) (x>=A7)
#define indietro_turno_due(x) ((x)>>16)
#define avanti_due(x) ((x)+16)
#define TRAVERSA_SECONDA TRAVERSA2
#define en_traversa_terza(x) ((x&070)==020)
#define TRAVERSA_SECONDA_SESTA traversa26
#define bitbordo_traversa_settima TRAVERSA7
#define bitbordo_traversa_ottava TRAVERSA8
#define BIANCO_A7 A7
#define BIANCO_H7 H7

#define cattura_en_passant cattura_valu[conto_pedone_bianco][conto_pedone_nero]
#define promozione_donna_cattura ((0x28<<24)+cattura_valu[conto_pedone_bianco][c])
#define promozione_cavallo_cattura ((0x1a<<24)+cattura_valu[conto_pedone_bianco][c])

#define arrocco_oo arrocco_bianco_oo
#define arrocco_ooo arrocco_bianco_ooo
#define BIANCO_F1G1 F1G1
#define BIANCO_C1D1 C1D1
#define BIANCO_B1C1D1 B1C1D1
#define BIANCO_E1 E1
#define BIANCO_C1 C1
#define BIANCO_G1 G1
#define sotto_promozione sotto_promozione_bianco

#define en_traversa_seconda(x) ((x&070)==010)
#define retto_cattura (((quadretto_fisso[di]&nonH)<<9)&bitbordo_occupato_nero&cel)
#define sinistra_cattura (((quadretto_fisso[di]&nonA)<<7)&bitbordo_occupato_nero&cel)
#define pedone_guardiano(x,y) (DINAMICO->attacco_bianco&quadretto_fisso[x] || ATTACO_colonna((y))&(bitbordo_bianco_torre|bitbordo_bianca_donna))
#define TRAVERSA_QUARTA_OTTAVA_noH (0x7f7f7f7f7f000000)
#define TRAVERSA_QUARTA_OTTAVA_noA (0xfefefefefe000000)
#define indietro_retto(x) ((x)-7)
#define indietro_retto_due(x) ((x)-15)
#define indietro_retto_tre(x) ((x)-23)
#define indietro_sinistro(x) ((x)-9)
#define indietro_sinistro_due(x) ((x)-17)
#define indietro_sinistro_tre(x) ((x)-25)
#define numero_traversa5 T5

#define numero_traversa2 T2
#define mio_pezzo PEZZO_BIANCO
#define tuo_pezzo PEZZO_NERO
#define indietro_due(x) ((x)-16)

#define tuo_pedone(x) ((x==conto_pedone_nero)?0xffffffffffffffff:0)
