#define mio_smp_nodo_pv ivan_smp_pv_node_black
#define tuo_smp_nodo_pv ivan_smp_pv_node_white
#define mio_smp_nodo_all ivan_smp_all_node_black
#define tuo_smp_nodo_all ivan_smp_all_node_white
#define mio_smp_nodo_cut ivan_smp_cut_node_black
#define tuo_smp_nodo_cut ivan_smp_cut_node_white

#define mio_pv_cerca_fine pv_cerca_fine_nero
#define mio_pv_cerca_fine_scacco pv_cerca_fine_scacco_nero
#define mio_cerca_fine_scacco cerca_fine_scacco_nero
#define mio_cerca_fine cerca_fine_nero
#define mio_cerca_mezzo cerca_mezzo_nero
#define mio_cerca_mezzo_scacco cerca_mezzo_scacco_nero
#define mio_escludo escludo_nero
#define mio_escludo_scacco escludo_scacco_nero
#define mio_nodo_tagliato nodo_tagliato_nero
#define mio_nodo_tagliato_scacco nodo_tagliato_scacco_nero
#define mio_nodo_totale nodo_totale_nero
#define mio_nodo_totale_scacco nodo_totale_scacco_nero
#define mio_nodo_pv nodo_pv_nero
#define mio_nodo_superiore nodo_superiore_nero
#define mio_alto cerca_alto_nero
#define mio_attaco DINAMICO->attacco_nero
#define tuo_attaco DINAMICO->attacco_bianco
#define mio_attaco_pedone attaco_pedone_nero
#define tuo_attaco_pedone attaco_pedone_bianco
#define tuo_pv_cerca_fine pv_cerca_fine_bianco
#define tuo_pv_cerca_fine_scacco pv_cerca_fine_scacco_bianco
#define tuo_cerca_fine cerca_fine_bianco
#define tuo_cerca_fine_scacco cerca_fine_scacco_bianco
#define tuo_cerca_mezzo cerca_mezzo_bianco
#define tuo_cerca_mezzo_scacco cerca_mezzo_scacco_bianco
#define tuo_escludo escludo_bianco
#define tuo_escludo_scacco escludo_scacco_bianco
#define tuo_nodo_tagliato nodo_tagliato_bianco
#define tuo_nodo_tagliato_scacco nodo_tagliato_scacco_bianco
#define tuo_nodo_totale nodo_totale_bianco
#define tuo_nodo_totale_scacco nodo_totale_scacco_bianco
#define tuo_nodo_pv nodo_pv_bianco
#define tuo_nodo_superiore nodo_superiore_bianco
#define tuo_alto cerca_alto_bianco
#define tuo_occupato bitbordo_occupato_bianco
#define bitbordo_tuo_pedone bitbordo_bianco_pedone
#define bitbordo_tuo_cavallo bitbordo_bianco_cavallo
#define bitbordo_tuo_chiaro bitbordo_bianco_chiaro
#define bitbordo_tuo_scuro bitbordo_bianco_scuro
#define bitbordo_tuo_alfiere (bitbordo_tuo_chiaro|bitbordo_tuo_scuro)
#define bitbordo_tuo_torre bitbordo_bianco_torre
#define bitbordo_tuo_donna bitbordo_bianca_donna
#define bitbordo_tuo_re bitbordo_bianco_re
#define mio_occupato bitbordo_occupato_nero
#define bitbordo_mio_pedone bitbordo_nero_pedone
#define bitbordo_mio_cavallo bitbordo_nero_cavallo
#define bitbordo_mio_chiaro bitbordo_nero_chiaro
#define bitbordo_mio_scuro bitbordo_nero_scuro
#define bitbordo_mio_alfiere (bitbordo_mio_chiaro|bitbordo_mio_scuro)
#define bitbordo_mio_torre bitbordo_nero_torre
#define bitbordo_mio_donna bitbordo_nera_donna
#define bitbordo_mio_re bitbordo_nero_re
#define mio_quadretto_re POSIZIONE->nero_re_quadretto
#define tuo_quadretto_re POSIZIONE->bianco_re_quadretto
#define conto_tuo_pedone conto_pedone_bianco
#define conto_tuo_cavallo conto_cavallo_bianco
#define conto_tuo_chiaro conto_chiaro_bianco
#define conto_tuo_scuro conto_scuro_bianco
#define conto_tuo_torre conto_torre_bianco
#define conto_tuo_donna conto_donna_bianca
#define conto_tuo_re conto_re_bianco
#define conto_mio_pedone conto_pedone_nero
#define conto_mio_cavallo conto_cavallo_nero
#define conto_mio_chiaro conto_chiaro_nero
#define conto_mio_scuro conto_scuro_nero
#define conto_mio_torre conto_torre_nero
#define conto_mio_donna conto_donna_nera
#define conto_mio_re conto_re_nero
#define tuo_re_scacco DINAMICO->bianco_re_scacco
#define mio_cattura cattura_nera
#define mio_ordinaria ordinaria_nera
#define mio_guadagno guadagno_nero
#define mio_evasione evasione_nero
#define mio_scacco_zitto scacco_zitto_nero
#define mio_SEE SEE_nera
#define FARE fare_nero
#define ANNULLA annullare_nero
#define mossa_illegale mossa_nero_in_scacco
#define mossa_scacco mossa_bianco_in_scacco
#define mio_garantire garantire_nero
#define mio_prossimo prossimo_nero
#define mio_nullo ((DINAMICO->pietras)&1)
#define TRAVERSA_SESTA(x) ((x)<=H3)
#define TRAVERSA_QUARTA(x) ((x)<=H5)
#define pedone_libero pedone_libero_nero
#define mio_xray (DINAMICO->nero_xray)
#define tuo_xray (DINAMICO->bianco_xray)
#define mio_xray_lista xray_nero_lista
#define tuo_xray_lista xray_bianco_lista
#define mio_re_scacco DINAMICO->nero_re_scacco
#define mio_conto conto_nero
#define mio_conto_fuggio conto_nero_fuggio
#define SCACCO nero_in_scacco

#define TRAVERSA_OTTAVA(x) (x<=H1)
#define cattura_retta ((bitbordo_nero_pedone&~COLONNAh)>>7)
#define di_sinistra(x) (((x)+7)<<6)
#define cattura_sinistra ((bitbordo_nero_pedone&~COLONNAa)>>9)
#define di_retto(x) (((x)+9)<<6)
#define avanti(x) ((x)-8)
#define avanti_sinistra(x) ((x)-9)
#define avanti_retto(x) ((x)-7)
#define indietro(x) ((x)+8)
#define avanti_turno(x) ((x)>>8)
#define indietro_turno(x) ((x)<<8)
#define TRAVERSA_SETTIMA(x) (x<=H2)
#define indietro_turno_due(x) ((x)<<16)
#define avanti_due(x) ((x)-16)
#define TRAVERSA_SECONDA TRAVERSA7
#define en_traversa_terza(x) ((x&070)==050)
#define bitbordo_traversa_quarta TRAVERSA5
#define TRAVERSA_SECONDA_SESTA traversa37
#define bitbordo_traversa_settima TRAVERSA2
#define bitbordo_traversa_ottava TRAVERSA1
#define BIANCO_A7 A2
#define BIANCO_H7 H2

#define cattura_en_passant cattura_valu[conto_pedone_nero][conto_pedone_bianco]
#define promozione_donna_cattura ((0x28<<24)+cattura_valu[conto_pedone_nero][c])
#define promozione_cavallo_cattura ((0x1a<<24)+cattura_valu[conto_pedone_nero][c])

#define arrocco_oo arrocco_nero_oo
#define arrocco_ooo arrocco_nero_ooo
#define BIANCO_F1G1 F8G8
#define BIANCO_C1D1 C8D8
#define BIANCO_B1C1D1 B8C8D8
#define BIANCO_E1 E8
#define BIANCO_C1 C8
#define BIANCO_G1 G8
#define sotto_promozione sotto_promozione_nero

#define en_traversa_seconda(x) ((x&070)==060)
#define retto_cattura (((quadretto_fisso[di]&nonH)>>7)&bitbordo_occupato_bianco&cel)
#define sinistra_cattura (((quadretto_fisso[di]&nonA)>>9)&bitbordo_occupato_bianco&cel)
#define pedone_guardiano(x,y) (DINAMICO->attacco_nero&quadretto_fisso[x] || ATTACO_colonna((y))&(bitbordo_nero_torre|bitbordo_nera_donna))
#define TRAVERSA_QUARTA_OTTAVA_noH (0x0000007f7f7f7f7f)
#define TRAVERSA_QUARTA_OTTAVA_noA (0x000000fefefefefe)
#define indietro_retto(x) ((x)+9)
#define indietro_retto_due(x) ((x)+17)
#define indietro_retto_tre(x) ((x)+25)
#define indietro_sinistro(x) ((x)+7)
#define indietro_sinistro_due(x) ((x)+15)
#define indietro_sinistro_tre(x) ((x)+23)
#define numero_traversa5 T4

#define numero_traversa2 T7
#define mio_pezzo PEZZO_NERO
#define tuo_pezzo PEZZO_BIANCO
#define indietro_due(x) ((x)+16)

#define tuo_pedone(x) ((x==conto_pedone_bianco)?0xffffffffffffffff:0)
