#undef mio_smp_nodo_pv
#undef tuo_smp_nodo_pv
#undef mio_smp_nodo_all
#undef tuo_smp_nodo_all
#undef mio_smp_nodo_cut
#undef tuo_smp_nodo_cut

#undef mio_pv_cerca_fine
#undef mio_pv_cerca_fine_scacco
#undef mio_cerca_fine
#undef mio_cerca_fine_scacco
#undef mio_cerca_mezzo
#undef mio_cerca_mezzo_scacco
#undef mio_escludo
#undef mio_escludo_scacco
#undef mio_nodo_tagliato
#undef mio_nodo_tagliato_scacco
#undef mio_nodo_totale
#undef mio_nodo_totale_scacco
#undef mio_nodo_pv
#undef mio_nodo_superiore
#undef mio_alto
#undef mio_attaco
#undef tuo_attaco
#undef mio_attaco_pedone
#undef tuo_attaco_pedone
#undef tuo_pv_cerca_fine
#undef tuo_pv_cerca_fine_scacco
#undef tuo_cerca_fine
#undef tuo_cerca_fine_scacco
#undef tuo_cerca_mezzo
#undef tuo_cerca_mezzo_scacco
#undef tuo_escludo
#undef tuo_escludo_scacco
#undef tuo_nodo_tagliato
#undef tuo_nodo_tagliato_scacco
#undef tuo_nodo_totale
#undef tuo_nodo_totale_scacco
#undef tuo_nodo_pv
#undef tuo_nodo_superiore
#undef tuo_alto
#undef tuo_occupato
#undef bitbordo_tuo_pedone
#undef bitbordo_tuo_cavallo
#undef bitbordo_tuo_chiaro
#undef bitbordo_tuo_scuro
#undef bitbordo_tuo_torre
#undef bitbordo_tuo_donna
#undef bitbordo_tuo_re
#undef mio_occupato
#undef bitbordo_mio_pedone
#undef bitbordo_mio_cavallo
#undef bitbordo_mio_chiaro
#undef bitbordo_mio_scuro
#undef bitbordo_mio_torre
#undef bitbordo_mio_donna
#undef bitbordo_mio_re
#undef mio_quadretto_re
#undef tuo_quadretto_re
#undef conto_tuo_pedone
#undef conto_tuo_cavallo
#undef conto_tuo_chiaro
#undef conto_tuo_scuro
#undef conto_tuo_torre
#undef conto_tuo_donna
#undef conto_tuo_re
#undef conto_mio_pedone
#undef conto_mio_cavallo
#undef conto_mio_chiaro
#undef conto_mio_scuro
#undef conto_mio_torre
#undef conto_mio_donna
#undef conto_mio_re
#undef tuo_re_scacco
#undef mio_cattura
#undef mio_ordinaria
#undef mio_guadagno
#undef mio_evasione
#undef mio_scacco_zitto
#undef mio_SEE
#undef FARE
#undef ANNULLA
#undef mossa_illegale
#undef mossa_scacco
#undef mio_garantire
#undef mio_prossimo
#undef mio_nullo
#undef TRAVERSA_SESTA
#undef TRAVERSA_QUARTA
#undef bitbordo_traversa_quarta
#undef pedone_libero
#undef mio_xray
#undef tuo_xray
#undef mio_xray_lista
#undef tuo_xray_lista
#undef mio_re_scacco
#undef mio_conto
#undef mio_conto_fuggio
#undef SCACCO

#undef TRAVERSA_OTTAVA
#undef cattura_retta
#undef di_sinistra
#undef cattura_sinistra
#undef di_retto
#undef avanti
#undef avanti_sinistra
#undef avanti_retto
#undef indietro
#undef avanti_turno
#undef indietro_turno
#undef TRAVERSA_SETTIMA
#undef indietro_turno_due
#undef avanti_due
#undef TRAVERSA_SECONDA
#undef TRAVERSA_SECONDA_SESTA
#undef en_traversa_terza
#undef TRAVERSA_SECONDA_SESTA
#undef bitbordo_traversa_settima
#undef bitbordo_traversa_ottava
#undef BIANCO_A7
#undef BIANCO_H7

#undef cattura_en_passant
#undef promozione_donna_cattura
#undef promozione_cavallo_cattura

#undef arrocco_oo
#undef arrocco_ooo
#undef BIANCO_F1G1
#undef BIANCO_C1D1
#undef BIANCO_B1C1D1
#undef BIANCO_E1
#undef BIANCO_C1
#undef BIANCO_G1
#undef sotto_promozione

#undef en_traversa_seconda
#undef retto_cattura
#undef sinistra_cattura
#undef pedone_guardiano
#undef TRAVERSA_QUARTA_OTTAVA_noH
#undef TRAVERSA_QUARTA_OTTAVA_noA
#undef indietro_retto
#undef indietro_retto_due
#undef indietro_retto_tre
#undef indietro_sinistro
#undef indietro_sinistro_due
#undef indietro_sinistro_tre
#undef numero_traversa5

#undef numero_traversa2
#undef mio_pezzo
#undef tuo_pezzo
#undef indietro_due

#undef tuo_pedone
